#!/bin/bash

#Install nginx for the healtchecks
sudo apt-get -y install nginx

#Enable packet forwarding
sudo sysctl -w net.ipv4.ip_forward=1

#Check and create routing table for ens5 interface
TABLE_EXISTS="$(awk '/100 ens5_table/ {print}' \
    /etc/iproute2/rt_tables | wc -l)"
if [[ "$TABLE_EXISTS" -eq 0 ]]; then
   echo "100 ens5_table" >> /etc/iproute2/rt_tables;
fi

#Configure IPTABLES to mark traffic arriving on ens5
sudo iptables -A PREROUTING -t mangle -i ens5 -j MARK --set-mark 1
sudo iptables -A PREROUTING -t mangle -i ens5 -j CONNMARK --save-mark
sudo iptables -A OUTPUT -t mangle -j CONNMARK --restore-mark

#Add policy routing rule to ens5_table
sudo ip rule add priority 1000 fwmark 0x1 table ens5_table

#Add routes to ens5_table
cat <<EOF > ./addRoutes.sh
#! /bin/bash
sleep 10
sudo ip route add table ens5_table 130.211.0.0/22 via 10.1.0.1 dev ens5
sudo ip route add table ens5_table 35.191.0.0/16 via 10.1.0.1 dev ens5
sudo ip route add to 10.2.0.0/24 via 10.1.0.1
sudo ip route add to 10.4.0.0/24 via 10.1.0.1
sudo ip route add to 10.250.0.0/24 via 10.1.0.1
sudo ip route add to 10.251.0.0/24 via 10.1.0.1
EOF
chmod 755 ./addRoutes.sh
./addRoutes.sh & disown

#Disable source address checks on ens5
sysctl -w net.ipv4.conf.all.rp_filter=0
sysctl -w net.ipv4.conf.ens5.rp_filter=0

#Configure NAT
sudo iptables -t nat -A POSTROUTING -o ens4 -j MASQUERADE
sudo iptables -t nat -A POSTROUTING -o ens5 -j MASQUERADE

#install tools
sudo apt-get -y install traceroute
sudo apt-get -y install conntrack
sudo apt-get -y install tcpdump